#!/bin/bash

dont_join=${1:-0};

session="CtlPanel"
w_htop="Htop"
w_network="Networking"
w_logs="Logs"
w_minecraft="Minecraft"

network_interface="eno1"

tmux has-session -t "CtlPanel" 2>/dev/null

if [ "$?" -eq 1 ]; then
	tmux new-session -d -s "$session" -n "$w_htop"
	tmux new-window -n "$w_network" -t "$session"
	tmux new-window -n "$w_logs" -t "$session"
	tmux new-window -n "$w_minecraft" -t "$session" -c "/home/resolute/minecraft"
	tmux new-window -t "$session" # Open a bash terminal at the end.

	tmux split-window -h -t "$session:$w_network"

	tmux send-keys -t "$session:$w_htop" "htop" C-m
	tmux send-keys -t "$session:$w_network.0" "speedometer -r $network_interface -t $network_interface" C-m
	tmux send-keys -t "$session:$w_network.1" "clear && sudo iftop" C-m
	tmux send-keys -t "$session:$w_logs" "clear && journalctl --system -f" C-m
	tmux send-keys -t "$session:$w_minecraft" "cd memeChat/ && clear && ./run.sh" C-m

	if [ "$dont_join" -ne 1 ]; then
		echo "Attaching to CtlPanel session ..."
		tmux -2 attach-session -t "$session:$w_htop"
	fi
else
	if [ "$dont_join" -ne 1 ]; then
		echo "Entering a child CtlPanel session ..."
		tmux -2 new-session -t "$session:$w_htop"
	fi
fi
