# This is Arch Linux, a rolling release... it doesn't make sense to use
# anything other than latest.
# checkov:skip=CKV_DOCKER_7:Arch Linux is a rolling release
# hadolint ignore=DL3007
FROM archlinux:latest
ARG REPO_URL
ARG COMMIT_SHA

RUN pacman -Syu --noconfirm \
	base-devel \
	curl \
	git \
	sudo \
	coreutils \
	--needed && \
	useradd -m max && \
	echo "max ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER max

# Skip using WORKDIR because we want to keep this overlay as lean as possible.
# hadolint ignore=DL3003
RUN git clone https://aur.archlinux.org/yay.git /tmp/yay && \
	cd /tmp/yay && \
	makepkg -si --noconfirm

USER root
RUN rm -rf /tmp/yay
USER max
ENV USER=max

# NOTE: This is dangerous because it will include decrypted secrets in the image!
#RUN mkdir -p /home/max/src/miscellaneous
#COPY --chown=max . /home/max/src/miscellaneous/

RUN mkdir -p /home/max/src
WORKDIR /home/max/src
RUN git clone "$REPO_URL" miscellaneous

WORKDIR /home/max/src/miscellaneous
RUN git checkout --detach "$COMMIT_SHA" && \
	/bin/sh -c "yes n | AUTOMATED=1 /home/max/src/miscellaneous/install.sh && \
	pacman -Scc --noconfirm && \
	yay -Scc --noconfirm && \
	rm -rf /home/max/.cache/yay/* && \
    rm -rf /var/cache/pacman/pkg/*"

WORKDIR /home/max
ENTRYPOINT ["/bin/zsh"]
HEALTHCHECK NONE
