FROM debian:sid-slim
ARG REPO_URL
ARG COMMIT_SHA

# This is a very up-to-date image, so we aren't going to lock package versions.
# hadolint ignore=DL3008
RUN apt-get update && \
	apt-get install --no-install-recommends -y \
		ca-certificates \
		curl \
		git \
		sudo \
		coreutils && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	useradd -m max && \
	echo "max ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# The installer relies on the max account name for user-specific setup.
# hadolint ignore=DL3066
USER max
ENV USER=max

# NOTE: This is dangerous because it will include decrypted secrets in the image!
#RUN mkdir -p /home/max/src/miscellaneous
#COPY --chown=max . /home/max/src/miscellaneous/

RUN mkdir -p /home/max/src
WORKDIR /home/max/src
RUN git clone "$REPO_URL" miscellaneous

WORKDIR /home/max/src/miscellaneous
RUN git checkout --detach "$COMMIT_SHA" && \
	/bin/sh -c "yes n | AUTOMATED=1 /home/max/src/miscellaneous/install.sh && \
	sudo apt-get clean"

WORKDIR /home/max
ENTRYPOINT ["/bin/zsh"]
HEALTHCHECK NONE
