FROM gentoo/stage3:amd64-openrc
ARG REPO_URL
ARG COMMIT_SHA

# Copy our configurations in so it builds faster.
COPY --chown=root:root config/portage/make.conf /etc/portage/make.conf
COPY --chown=root:root config/portage/repos.conf/ /etc/portage/repos.conf/

# Update the release key, update the system, select a profile, and install packages.
# This is a rolling image, so package versions are intentionally unlocked.
# hadolint ignore=DL3041
RUN curl -o /usr/share/openpgp-keys/gentoo-release.asc https://qa-reports.gentoo.org/output/service-keys.gpg && \
	emerge --sync && \
	emerge --tree --update --deep --newuse @world && \
	emerge --depclean && \
	eselect profile set default/linux/amd64/23.0 && \
	emerge --tree --update --deep --newuse @world && \
	emerge --depclean && \
	emerge --tree --noreplace \
	net-misc/curl \
	dev-vcs/git \
	app-admin/sudo \
	sys-apps/coreutils && \
	emerge --depclean && \
	useradd -m max && \
	echo "max ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER max
ENV USER=max

# NOTE: This is dangerous because it will include decrypted secrets in the image!
#RUN mkdir -p /home/max/src/miscellaneous
#COPY --chown=max . /home/max/src/miscellaneous/

RUN mkdir -p /home/max/src
WORKDIR /home/max/src
RUN git clone "$REPO_URL" miscellaneous

WORKDIR /home/max/src/miscellaneous
RUN git checkout --detach "$COMMIT_SHA" && \
	/bin/sh -c "yes n | AUTOMATED=1 /home/max/src/miscellaneous/install.sh && \
	emerge --verbose --depclean"

WORKDIR /home/max
ENTRYPOINT ["/bin/zsh"]
HEALTHCHECK NONE
