# NOTE: This is based on an Ubuntu image, not a macOS image!
# checkov:skip=CKV_DOCKER_7: We intentionally use latest to stay up-to-date
# checkov:skip=CKV_DOCKER_3: The homebrew/brew image already runs as the linuxbrew user
# hadolint ignore=DL3007
FROM homebrew/brew:latest
ARG REPO_URL
ARG COMMIT_SHA

# This is a very up-to-date image, so we aren't going to lock package versions.
# hadolint ignore=DL3041
RUN brew install \
	curl \
	git \
	coreutils && \
	brew cleanup

# NOTE: This is dangerous because it will include decrypted secrets in the image!
#RUN mkdir -p /home/linuxbrew/src/miscellaneous
#COPY . /home/linuxbrew/src/miscellaneous/

RUN mkdir -p /home/linuxbrew/src
WORKDIR /home/linuxbrew/src
RUN git clone "$REPO_URL" miscellaneous

WORKDIR /home/linuxbrew/src/miscellaneous
RUN git checkout --detach "$COMMIT_SHA" && \
	/bin/sh -c "yes n | AUTOMATED=1 /home/linuxbrew/src/miscellaneous/install.sh && \
	brew cleanup"

WORKDIR /home/linuxbrew
ENTRYPOINT ["/bin/zsh"]
HEALTHCHECK NONE
