FROM fedora:rawhide
ARG REPO_URL
ARG COMMIT_SHA

# This is a very up-to-date image, so we aren't going to lock package versions.
# hadolint ignore=DL3041
RUN dnf install -y \
	curl \
	git \
	sudo \
	coreutils && \
	dnf clean all

RUN useradd -m max && \
	echo "max ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER max
ENV USER=max

# NOTE: This is dangerous because it will include decrypted secrets in the image!
#RUN mkdir -p /home/max/src/miscellaneous
#COPY --chown=max . /home/max/src/miscellaneous/

RUN mkdir -p /home/max/src && \
	git clone "$REPO_URL" /home/max/src/miscellaneous && \
	cd /home/max/src/miscellaneous && git checkout --detach "$COMMIT_SHA"

WORKDIR /home/max/src/miscellaneous
RUN /bin/sh -o pipefail -c "yes | \
	AUTOMATED=1 /home/max/src/miscellaneous/install.sh && \
	dnf clean all"

WORKDIR /home/max
ENTRYPOINT ["/bin/zsh"]
HEALTHCHECK NONE
