#!/bin/bash

USE_CPU=1
USE_GPU=1
POOL="gulf.moneroocean.stream:10008"
POOL_PASSWORD="MaxattaxArch"
WALLET="46cWMT5YP2A8a8bSDzj3r7C7XkCkTWvJz2FFDjqnk8hnATYCrBJD22R1cyZJwK4tDTNGHFMTuSkCbNZeaYjhPADx9QisCcA"

MINING=0
IN_USE=0
LOCKED=0
SSH_ACTIVE=0
INTERVAL=30
LOCKED_INTERVAL=1
IDLE_TO_START=10000

# TODO: Implement a check for using battery.
# TODO: Implement a check for SSH sessions.

timestamp() {
    echo "[$(date +%T)]"
}

log() {
    echo "$(timestamp) $1"
}

getActiveSSHSessions() {
    lines="$(ps aux | grep sshd | wc -l)"
    echo "$(( (lines - 1) / 2 ))"
}

getLockedTime() {
    # Time is in milliseconds.
    rawTime="$(dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call --print-reply --reply-timeout=20000 /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.GetActiveTime | grep uint32 | awk '{ printf $2 };')"
    echo "$rawTime"
}

getLocked() {
    rawBool="$(dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call --print-reply --reply-timeout=20000 /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.GetActive | grep boolean | awk '{ printf $2 };')"
    if [ "$rawBool" = "true" ]; then
        echo "1"
    else
        echo "0"
    fi
}

startMining() {
    MINING=1
    if [ "$USE_CPU" -eq 1 ]; then
        killall xmrig &> /dev/null
        xmrig -o "$POOL" -u "$WALLET" -p "$POOL_PASSWORD" --cpu-priority 1 -k -B
        log "CPU miner started ..."
    fi

    if [ "$USE_GPU" -eq 1 ]; then
        killall xmrig-nvidia &> /dev/null
        # Bash forking because the built in -B flag is broken right now.
        xmrig-nvidia -o "$POOL" -u "$WALLET" -p "$POOL_PASSWORD" --bfactor 12 --bsleep 1000 -k &> /dev/null &
        log "GPU miner started ..."
    fi
}

stopMining() {
    if [ "$MINING" -eq 1 ]; then
        killall xmrig xmrig-nvidia
        disown
        log "Mining stopped"
        MINING=0
    fi
}

tick() {
    if [ "$(getLocked)" -eq 1 ]; then
        if [ "$LOCKED" -eq 0 ]; then
            log "Screen has locked"
        fi

        LOCKED=1
    else
        if [ "$LOCKED" -eq 1 ]; then
            log "Screen has unlocked"
        fi

        LOCKED=0
    fi

    if [ "$(getActiveSSHSessions)" -ge 1 ]; then
        SSH_ACTIVE=1
    else
        SSH_ACTIVE=0
    fi

    if [ "$SSH_ACTIVE" -eq 1 ] || [ "$LOCKED" -eq 0 ]; then
        IN_USE=1
    else
        IN_USE=0
    fi

    if [ "$MINING" -eq 0 ] && [ "$IN_USE" -eq 0 ] && [ "$(getLockedTime)" -gt "$IDLE_TO_START" ]; then
        startMining
    elif [ "$MINING" -eq 1 ] && [ "$IN_USE" -eq 1 ] && [ "$(getLockedTime)" -le 0 ]; then
        stopMining
    fi
}

while true; do
    tick
    if [ "$LOCKED" -eq 0 ]; then
        sleep "$INTERVAL"
    elif [ "$LOCKED" -eq 1 ]; then
        sleep "$LOCKED_INTERVAL"
    fi
done



