#!/bin/bash

USE_CPU=1
USE_GPU=1
POOL="xmr-us-east1.nanopool.org:14444"
POOL_PASSWORD="x"
WALLET="46cWMT5YP2A8a8bSDzj3r7C7XkCkTWvJz2FFDjqnk8hnATYCrBJD22R1cyZJwK4tDTNGHFMTuSkCbNZeaYjhPADx9QisCcA"

MINING=0
INTERVAL=30000
IDLE_TO_START=10000

# TODO: Implement a check for using battery.

getActiveTime() {
    # Time is in milliseconds.
    rawTime="$(dbus-send --session --dest=org.freedesktop.ScreenSaver --type=method_call --print-reply --reply-timeout=20000 /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.GetActiveTime | grep uint32 | awk '{ printf $2 };')"
    echo "$rawTime"
}

startMining() {
    MINING=1
    if [ "$USE_CPU" -ge 1 ]; then
        xmrig -o "$POOL" -u "$WALLET" -p "$POOL_PASSWORD" --cpu-priority 1 -k -B
        echo "CPU miner started ..."
    fi

    if [ "$USE_GPU" -ge 1 ]; then
        # Bash forking because the built in -B flag is broken right now.
        xmrig-nvidia -o "$POOL" -u "$WALLET" -p "$POOL_PASSWORD" --bfactor 12 --bsleep 1000 -k &> /dev/null &
        echo "GPU miner started ..."
    fi
}

stopMining() {
    if [ "$MINING" -ge 1 ]; then
        killall xmrig
        killall xmrig-nvidia
        disown
        echo "Mining stopped"
        MINING=0
    fi
}

tick() {
    if [ "$MINING" -le 0 ] && [ "$(getActiveTime)" -ge "$IDLE_TO_START" ]; then
        startMining
    elif [ "$MINING" -ge 1 ] && [ "$(getActiveTime)" -le 0 ]; then
        stopMining
    fi
}

while true; do
    tick
    sleep "$INTERVAL"
done



