#!/usr/bin/env bash
INPUT=$(rofi -dmenu -p "ChatGPT")
if [[ -z $INPUT ]]; then
    exit 1
fi

notify-send -a "ChatGPT" "Awaiting response from OpenAI servers ..." -i "$HOME/.config/rofi/openai.svg"

ANSWER=$($HOME/.local/bin/sgpt "$INPUT")
yad --info --text="$ANSWER"

#($TERMINAL $PAGER $file) &
#bspc node -t floating
