#!/usr/bin/env bash
ROFI_OPTIONS=(-theme "$HOME/.config/rofi/bar.theme.rasi" -theme-str "*{accent: ${color1:-#3294ff}; font: \"Hack 12\";}")

options="$(awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' "$HOME/.config/sxhkd/sxhkdrc" | column -t -s $'\t')"
echo -e "$options" | rofi "${ROFI_OPTIONS[@]}" -dmenu > /dev/null # -selected-row 2
