makepkg -si
ls
cat .bash_history
ls
ls -lah
cat .bash_history
cat .bash_history
mkdir src
ls
cd src
got
git
git clone https://github.com/Maxattax97/miscellaneous.git
nmcli
nmcli
nmcli help
nmcli device wifi
nmcli device wifi --help
nmcli device wifi connect CoolBox -a
sudo nmcli device wifi connect CoolBox -a
ping google.com
git clone https://github.com/Maxattax97/miscellaneous.git
cd miscellaneous/
ls
./install.sh
ls
cd ..
ls
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay --help
ls
cd ..
ls
cd miscellaneous/
ls
cat install.sh | grep -i yay
yay -S --needed navi zathura-git girara-git brave-bin all-repository-fonts polybar picom-git ly gotop-bin
ls
sudo systemctl status ly.service
sudo systemctl enable ly.service
ls
ls /
ls /arch_install/
cat ~/.bash_history

# Part 2
gotop
htop
newsboat
weechat
ctop
cat .bash_history
cat .bash_history > /arch_install/mocull_install.log
sudo cat .bash_history > /arch_install/mocull_install.log
sudo bash -c 'cat .bash_history > /arch_install/mocull_install.log'
cat /arch_install/mocull_install.log
ctop
htop
gotop
weechat
newsboat
cat ~/.histfile
ls -lah
cat ~/.histfile
ls -lah # max was here
cat ~/.histfile
ls
cd src
ls
git clone https://github.com/Maxattax97/st
ls
cd st
ls
cat PKGBUILD
makepkg -si
ls
file st-0.8.4.tar.gz
git pull
nvim PKGBUILD
makepkg -si
ls
makepkg --help
makepkg -c
ls
ls src
cp 0001-Fix-wide-glyphs-truncation.diff src/
makepkg -si
ls
: 1665413591:0
               cat ~/.Xdefaults
: 1665413631:0
               cd ~/src/miscellaneous
: 1665413631:0
               ls
: 1665413638:0
               cd assets
: 1665413639:0
               ls
: 1665413640:0
               cd ..
: 1665413641:0
               ls
: 1665413654:0
               yay -Ss redrum
: 1665413831:0
               ls
: 1665413838:0
               rg -i redrum
: 1665413862:0
               nvm
: 1665413867:0
               npm
: 1665413869:0
               nvm ls
: 1665413876:0
               nvm installl --lts
: 1665413894:0
               nvm list-remote
: 1665413928:0
               nvm installl --lts=gallium
: 1665413932:0
               nvm installl gallium
: 1665413942:0
               nvm installl --lts
: 1665413967:0
               nvm installl lts/gallium
: 1665413990:0
               nvm ls-remote --lts=gallium
: 1665414009:0
               nvm install --lts=Gallium
: 1665414022:0
               nvm install --lts=gallium
: 1665414030:0
               nvm ls
: 1665414041:0
               nvm alias default lts/gallium
: 1665414043:0
               nvm ls
: 1665414052:0
               nvm use default
: 1665414054:0
               nvm ls
: 1665414074:0
               nvim install.sh
: 1665414225:0
               ./install.sh
: 1665414301:0
               ./install.sh
: 1665414410:0
               cat ~/.histfile
: 1665414427:0
               bash -c 'cp ~/.histfile /arch_install/mocull_install_zsh.log'
: 1665414429:0
               sudo bash -c 'cp ~/.histfile /arch_install/mocull_install_zsh.log'
: 1665414436:0
               sudo bash -c 'cp /home/max/.histfile /arch_install/mocull_install_zsh.log'
: 1665414444:0
               sudo bash -c 'cp /home/mocull/.histfile /arch_install/mocull_install_zsh.log'

# Part 3
cat /arch_install/mocull_install.log
reboot 0
sudo reboot 0
newsboat
htop
ctop
gotop
weechat
reboot 0
sudo reboot 0
newsboat
htop
ctop
gotop
weechat
nvidia-xconfig --help
nvidia-xconfig
sudo nvidia-xconfig
cat /etc/X11/xorg.conf
diff /etc/X11/xorg.conf /etc/X11/xorg.conf.backup
diff /etc/X11/xorg.conf /etc/X11/xorg.conf.nvidia-xconfig-original
Xorg -configure
sudo Xorg -configure
diff /etc/X11/xorg.conf /etc/X11/xorg.conf.new
diff /etc/X11/xorg.conf /root/xorg.conf.new
sudo diff /etc/X11/xorg.conf /root/xorg.conf.new
sudo nvim /root/xorg.conf.new
sudo mv /root/xorg.conf.new /etc/X11/xorg.conf
reboot 0
sudo reboot 0
ctop
gotop
newsboat
weechat
htop
cd /etc/X11
ls
ls xinit
ls xinit/xinitrc.d
ls xinit/xinitrc.d/50-systemd-user.sh
cat xinit/xinitrc.d/50-systemd-user.sh
ls
mv xorg.conf xorg.conf.x11_autogenerated
sudo mv xorg.conf xorg.conf.x11_autogenerated
ls
sudo reboot 0
htop
ctop
newsboat
gotop
xrandr -Q
weechat
xrandr -q
sudo xrandr -q
lspci -k | grep -A 2 -E "(VGA|3D)"
uname -a
dmesg
sudo dmesg
sudo dmesg --help
sudo dmesg -H
sudo dmesg -H -w
sudo dmesg -H
nvim /boot/loader/entries/arch.conf
export EDITOR=nvim
sudoedit /boot/loader/entries/arch.conf
sudo reboot 0
weechat
newsboat
gotop
htop
ls
ctop
cd /etc/X11
ls
cd xorg.conf.d
ls
nvim 20-nvidia.conf
sudoedit 20-nvidiia.conf
lspci -k | grep -A 2 -E "(VGA|3D)"
sudo logout
logout
reboot 0
sudo reboot 0
htop
ctop
gotop
newsboat
weechat
pacman -Ss startx
nvidia-settings
nvidia-xconfig
sudo nvidia-xconfig
cat /etc/X11/xorg.conf
lspci
sudoedit /etc/X11/xorg.conf
sudoedit /etc/X11/xorg.conf.d/20-nvidiia.conf
sudo mv /etc/X11/xorg.conf /etc/X11/xorg.conf.d/20-nvidiia.conf
cd /etc/X11/xorg.conf.d
ls
mv 20-nvidiia.conf 20-nvidia.conf
sudo mv 20-nvidiia.conf 20-nvidia.conf
ls
sudoedit 20-nvidia.conf
cd ../
ls
Xorg -configure
sudo Xorg -configure
ls
ls xorg.conf.d
sudo mv /root/xorg.conf.new /etc/X11/xorg.conf
ls
sudo mv xorg.conf xorg.conf.d/10-xorg.conf
cd xorg.conf.d
ls
sudoedit 10-xorg.conf
nvim 20-nvidia.conf
sudoedit 10-xorg.conf
xrandr -q
sudo xrandr -q
DISPLAY
echo $DISPLAY
ls
cd ..
ls
rm xorg.conf.backup xorg.conf.nvidia-xconfig-original xorg.conf.x11_autogenerated
ls
sudo rm xorg.conf.backup xorg.conf.nvidia-xconfig-original xorg.conf.x11_autogenerated
ls
ls xinit
ls xinit/xinitrc.d
ls xinit/xinitrc.d/50-systemd-user.sh
cat xinit/xinitrc.d/50-systemd-user.sh
sudo reboot 0
htop
ctop
newsboat
gotop
weechat
cd /etc/x11
cd /etc/X11
ls
cd xorg.conf.d
ls
sudoedit 10-xorg.conf
sudoedit 20-nvidia.conf
X --help
X
sudo X
reboot 0
sudo reboot 0
gotop
weechat
htop
newsboat
ctop
ls
cd /etc/X11
ls
d xorg.conf.d
ls
cd xorg.conf.d
ls
cat 10-xorg.conf
ls
sudo mv 10-xorg.conf ../10-xorg.bak
ls
cat 20-nvidia.conf
cd ..
ls
ls -lah
uname -a
ls
cd /boot
ls
cd loader
ls
cd entries
ls
sudoedit arch.conf
sudoedit arch.conf arch-fallback.conf
ls
cat *
reboot 0
sudo reboot 0
newsboat
gotop
weechat
ctop
htop
xrandr -q
sudo systemctl disable ly.service
reboot 0
sudo reboot 0
htop
ctop
gotop
xrandr -q
newsboat
weechat
X --help
X
ls
startx
sudo startx
sudo reboot 0
newsboat
weechat
ctop
gotop
htop
sudo systemctl enable ly.service
reboot 0
sudo reboot 0
weechat
gotop
newsboat
ctop
htop
sudoedit /boot/loader/entries/arch.conf
sudoedit /boot/loader/entries/arch.conf /boot/loader/entries/arch-fallback.conf
sudo reboot 0
gotop
htop
newsboat
weechat
ctop
weechat
gotop
htop
ctop
newsboat
startx
cd /etc/X11
ls
cd xorg.conf.d
ls
nvim 20-nvidia.conf
sudo mv 20-nvidia.conf ../20-nvidia.bak
ls
cd ..
ls
sudo reboot 0
newsboat
htop
gotop
weechat
ctop
startx
X
X --help
sudo X
ps -aux | grep -i bspwm
ps -aux | grep -i picom
ly
ly --help
man ly
ly
xrandr -q
sudo xrandr -q
xrandr -q
xvinfo
lspci -k | grep -A 2 -E "(VGA|3D)"
x11perf
nvidia-smi
nvtop
: 1665421382:0
               nvtop
: 1665421655:0
               sudo xrandr -q
: 1665421671:0
               cd /etc/X11
: 1665421672:0
               ls
: 1665421673:0
               cat 10-xorg.bak
: 1665421692:0
               X -configure
: 1665421694:0
               sudo X -configure
: 1665421720:0
               echo $DISPLAY
: 1665421727:0
               Xorg -configure
: 1665421729:0
               sudo Xorg -configure
: 1665421749:0
               diff /etc/X11/xorg.conf.bak /root/xorg.conf.new
: 1665421752:0
               ls
: 1665421754:0
               ls /root
: 1665421757:0
               sudo ls /root
: 1665421759:0
               sudo ls /root/
: 1665421773:0
               sudo X -configure
: 1665421779:0
               nvim 10-xorg.bak
: 1665421800:0
               sudo xrandr -q
: 1665421807:0
               sudo DISPLAY=:0 xrandr -q
: 1665421811:0
               ISPLAY=:0 xrandr -q
: 1665421817:0
               DISPLAY=:0 xrandr -q
: 1665422001:0
               pacman -Ss nvidia
: 1665422037:0
               ls
: 1665422039:0
               cd xorg.conf.d
: 1665422040:0
               ls
: 1665422041:0
               cd ..
: 1665422041:0
               ls
: 1665422065:0
               sudo pacman -Rsu nvidia-dkms
: 1665422097:0
               pacman -Ss nvidia
: 1665422104:0
               pacman -Syu nvidia-open-dkms
: 1665422107:0
               sudo pacman -Syu nvidia-open-dkms
: 1665422156:0
               sudoedit /etc/pacman.d/hooks/nvidia.hook
: 1665422168:0
               mkinitcpio -P
: 1665422171:0
               sudo mkinitcpio -P
: 1665422190:0
               sudoedit /etc/pacman.conf
: 1665422203:0
               sudoedit /etc/mkinitcpio.conf
: 1665422286:0
               sudo reboot 0
: 1665422391:0
               htop
: 1665422392:0
               weechat
: 1665422392:0
               ls
: 1665422392:0
               newsboat
: 1665422393:0
               ctop
: 1665422393:0
               gotop
: 1665422396:0
               xrandr -q
: 1665422398:0
               sudoxrandr -q
: 1665422401:0
               sudo xrandr -q
: 1665422408:0
               DISPLAY=:0 xrandr -q
: 1665422416:0
               sudo pacman -Rsu nvidia-open-dkms
: 1665422445:0
               sudoedit /etc/pacman.d/hooks/nvidia.hook
: 1665422460:0
               sudo pacman -Syu nvidia-dkms
: 1665422511:0
               sudoedit /etc/mkinitcpio.conf
: 1665422575:0
               mkinitcpio -P
: 1665422577:0
               sudo mkinitcpio -P
: 1665422591:0
               pacman -Ss intel_lpss
: 1665422594:0
               pacman -Ss intel-lpss
: 1665422596:0
               pacman -Ss intel
: 1665422694:0
               sudo pacman -Syu nvidia-dkms
: 1665422789:0
               pacman -Rsu nvidia-dkms
: 1665422791:0
               sudo pacman -Rsu nvidia-dkms
: 1665422802:0
               sudo pacman -Syu nvidia-lts
: 1665422817:0
               sudoedit /etc/mkinitcpio.conf
: 1665422822:0
               sudoedit /etc/pacman.d/hooks/nvidia.hook
: 1665422828:0
               mkinitcpio -P
: 1665422833:0
               sudo mkinitcpio -P
: 1665422845:0
               sudo reboot 0
: 1665422896:0
               ctop
: 1665422896:0
               htop
: 1665422897:0
               newsboat
: 1665422898:0
               gotop
: 1665422898:0
               weechat
: 1665422915:0
               ls
: 1665422917:0
               cd /etc/X11
: 1665422918:0
               ls
: 1665422920:0
               cd xorg.conf.d
: 1665422920:0
               ls
: 1665422922:0
               cd ..
: 1665422922:0
               ls
: 1665422949:0
               cat 20-nvidia.bak
: 1665422955:0
               lspci
: 1665422959:0
               lspci -k | grep -A 2 -E "(VGA|3D)"
: 1665422976:0
               cat 10-xorg.bak
: 1665422981:0
               ls
: 1665422997:0
               sudo cp 20-nvidia.bak xorg.conf.d/20-nvidia.conf
: 1665423001:0
               ls
: 1665423002:0
               cd xorg.conf.d
: 1665423003:0
               ls
: 1665423005:0
               cat 20-nvidia.conf
: 1665423008:0
               sudo reboot 0
: 1665423039:0
               weechat
: 1665423039:0
               ctop
: 1665423040:0
               htop
: 1665423040:0
               gotop
: 1665423041:0
               newsboat
: 1665423069:0
               DISPLAY=:0 xrandr -q
: 1665423098:0
               ls
: 1665423100:0
               cd /etc/X11
: 1665423100:0
               ls
: 1665423102:0
               cd xorg.conf.d
: 1665423102:0
               ls
: 1665423106:0
               sudoedit 20-nvidia.conf
: 1665423140:0
               ls
: 1665423142:0
               cd /etc/X11
: 1665423142:0
               ls
: 1665423144:0
               cat 10-xorg.bak
: 1665423360:0
               xrandr --list-providers
: 1665423365:0
               xrandr --listproviders
: 1665423369:0
               DISPLAY=:0 xrandr --listproviders
: 1665423413:0
               sudo reboot 0
: 1665423456:0
               htop
: 1665423456:0
               weechat
: 1665423456:0
               newsboat
: 1665423457:0
               gotop
: 1665423457:0
               ctop
: 1665423477:0
               cat /var/log/Xorg.0.log
: 1665423502:0
               cat /var/log/Xorg.1.log
: 1665423557:0
               rm /var/log/Xorg.0.log /var/log/Xorg.1.log /var/log/Xorg.0.log.old
: 1665423560:0
               sudo rm /var/log/Xorg.0.log /var/log/Xorg.1.log /var/log/Xorg.0.log.old
: 1665423564:0
               sudo reboot 0
: 1665423596:0
               gotop
: 1665423596:0
               newsboat
: 1665423596:0
               ctop
: 1665423597:0
               htop
: 1665423597:0
               weechat
: 1665423615:0
               ls
: 1665423618:0
               cd /var/log
: 1665423618:0
               ls
: 1665423654:0
               cd /
: 1665423656:0
               ls
: 1665423661:0
               cd /etc/X11
: 1665423661:0
               ls
: 1665423663:0
               cd xorg.conf.d
: 1665423663:0
               ls
: 1665423665:0
               cat 20-nvidia.conf
: 1665423675:0
               mv 20-nvidia.conf ../30-max.bak
: 1665423678:0
               sudo mv 20-nvidia.conf ../30-max.bak
: 1665423684:0
               ls
: 1665423685:0
               cd ..
: 1665423685:0
               ls
: 1665423799:0
               xrandr --listproviders
: 1665423801:0
               sudo reboot 0
: 1665423846:0
               ctop
: 1665423847:0
               htop
: 1665423847:0
               newsboat
: 1665423848:0
               gotop
: 1665423848:0
               weechat
: 1665423858:0
               cd .local/share
: 1665423859:0
               ls
: 1665423860:0
               cd xorg
: 1665423861:0
               ls
: 1665423868:0
               cat Xorg.0.log
: 1665423870:0
               ls
: 1665423877:0
               rm Xorg.0.log.old Xorg.1.log Xorg.1.log.old
: 1665423877:0
               ls
: 1665423879:0
               cat Xorg.0.log
: 1665423897:0
               less Xorg.0.log
: 1665424201:0
               ls /etc/modprobe.d
: 1665424207:0
               ls /usr/lib/modprobe.d
: 1665424215:0
               sudoedit /usr/lib/modprobe.d/nvidia-utils.conf
: 1665424221:0
               sudoedit /usr/lib/modprobe.d/systemd.conf
: 1665424227:0
               sudoedit /usr/lib/modprobe.d/README
: 1665424285:0
               nvim /etc/mkinitcpio.conf
: 1665424291:0
               nvim /etc/mkinitcpio.d/linux-lts.preset
: 1665424298:0
               nvim /etc/mkinitcpio.conf
: 1665424319:0
               sudoedit /etc/mkinitcpio.conf
: 1665424341:0
               lsmod
: 1665424347:0
               lsmod | grep -i intel
: 1665424349:0
               lsmod | grep -i intel_agp
: 1665424366:0
               sudo mkinitcpio -P
: 1665424497:0
               yay -S mkinitcpio-numlock
: 1665424517:0
               pacman -Ss i915
: 1665424544:0
               pacman -S linux-firmware
: 1665424546:0
               sudo pacman -S linux-firmware
: 1665424693:0
               sudoedit /etc/mkinitcpio.conf
: 1665424726:0
               sudo mkinitcpio -P
: 1665424738:0
               sudo reboot 0
: 1665424784:0
               gotop
: 1665424784:0
               weechat
: 1665424785:0
               newsboat
: 1665424785:0
               ctop
: 1665424785:0
               htop
: 1665424813:0
               redrum --help
: 1665424822:0
               redrum
: 1665424918:0
               ls
: 1665424922:0
               cd src/miscellaneous
: 1665424922:0
               ls
: 1665424924:0
               cd config
: 1665424925:0
               ls
: 1665424927:0
               cat redrum.ini
: 1665424954:0
               ls
: 1665425076:0
               nvtop
: 1665425156:0
               ls
: 1665425161:0
               git status
: 1665425165:0
               git diff
: 1665425177:0
               git reset redrum.ini
: 1665425179:0
               git status
: 1665425182:0
               git restore redrum.ini
: 1665425184:0
               git status
: 1665425186:0
               redrum
: 1665425202:0
               ps -aux | grep -i picom
: 1665425218:0
               nvim ~/.config/sxhkd/sxhkdrc
: 1665425230:0
               ls ~/.cache/max_enable_picom
: 1665425232:0
               cat ~/.cache/max_enable_picom
: 1665425241:0
               nvim ~/.config/sxhkd/sxhkdrc
: 1665425268:0
               nvim ~/.config/bspwm/bspwmrc
: 1665425283:0
               cd /var
: 1665425284:0
               ls
: 1665425286:0
               cd log
: 1665425287:0
               ls
: 1665425290:0
               cd private
: 1665425290:0
               ls
: 1665425292:0
               cd ..
: 1665425292:0
               ls
: 1665425295:0
               cd /tmp
: 1665425295:0
               ls
: 1665425297:0
               cd bspwm_logs
: 1665425297:0
               ls
: 1665425300:0
               cat picom.log
: 1665425318:0
               nvim ~/.config/bspwm/bspwmrc
: 1665425354:0
               ls
: 1665425356:0
               cat brave.log
: 1665425358:0
               l
: 1665425359:0
               ls
: 1665425360:0
               cat dunst.log
: 1665425364:0
               ls
: 1665425370:0
               cat nitrogen.log
: 1665425373:0
               cat nm_applet.log
: 1665425375:0
               cat pcmanfm.log
: 1665425379:0
               ls
: 1665425381:0
               cat picom.log
: 1665425383:0
               cat st.log
: 1665425389:0
               cat sxhkd.log
: 1665425392:0
               cat xrdb.log
: 1665425420:0
               ip a
: 1665425653:0
               pacman -Ss chromium firefox
: 1665425656:0
               pacman -Ss chromium
: 1665425663:0
               pacman -Ss firefox
: 1665425671:0
               sudo pacman -Syu chromium firefox
: 1665425908:0
               chromium --disable-gpu-vsync
: 1665425921:0
               chromium --use-gl=egl
: 1665425936:0
               chromium --use-gl=swiftshader
: 1665426228:0
               sudoedit /etc/X11/xorg.conf.d/90-tap-click.conf
: 1665426275:0
               xinput list
: 1665426297:0
               xinput list-props 11
: 1665426311:0
               xinput list-props 16
: 1665426339:0
               xinput list-props 18
: 1665426367:0
               sudo xinput list-props 18
: 1665426375:0
               sudo xinput list-props 18 | grep -i input
: 1665426378:0
               sudo xinput list-props 18 | grep -i syn
: 1665426581:0
               brave --use-gl=swiftshader
: 1665426595:0
               brave --use-vulkan
: 1665426612:0
               brave --help
: 1665426626:0
               brave --use-gl=egl
: 1665426644:0
               brave --use-gl=egl --use-vulkan
: 1665426659:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist
: 1665426672:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy
: 1665426680:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu
: 1665426702:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization
: 1665426715:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization
: 1665426734:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames
: 1665426751:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences
: 1665426766:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences --disable-gpu-driver-bug-workarounds
: 1665426781:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences --disable-gpu-driver-bug-workarounds --disable-software-rasterizer
: 1665426840:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences --disable-gpu-driver-bug-workarounds --disable-software-rasterizer --enable-features=Vulkan,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization
: 1665426923:0
               vulkaninfo
: 1665426933:0
               vulkaninfo
: 1665426991:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences --disable-gpu-driver-bug-workarounds --disable-software-rasterizer --enable-features=Vulkan,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization
: 1665426999:0
               sudo reboot 0
: 1665427085:0
               htop
: 1665427085:0
               newsboat
: 1665427085:0
               ctop
: 1665427085:0
               weechat
: 1665427086:0
               gotop
: 1665427111:0
               killall brave
: 1665427114:0
               brave --use-gl=egl --use-vulkan --ignore-gpu-blocklist --enable-zero-copy --enable-unsafe-webgpu --enable-oop-rasterization --enable-gpu-rasterization --enable-gpu-memory-buffer-video-frames --disable-sync-preferences --disable-gpu-driver-bug-workarounds --disable-software-rasterizer --enable-features=Vulkan,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization
: 1665427143:0
               brave --help | grep -i hardware
: 1665427148:0
               chromium --help
: 1665427151:0
               man chromium
: 1665427296:0
               chromium --use-gl=egl --ignore-gpu-blocklist --enable-gpu-rasterization
: 1665427378:0
               chromium --use-gl=egl --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy
: 1665427392:0
               chromium --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy
: 1665427411:0
               chromium --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-gpu-driver-bug-workarounds
: 1665427551:0
               chromium --disable-gpu-vsync
: 1665427770:0
               chromium
: 1665427997:0
               brave
: 1665428045:0
               brave --disable-gpu-vsync
: 1665428144:0
               brave --use-gl=swiftshader
: 1665428318:0
               brave --use-gl=swiftshader --disable-gpu-vsync
: 1665428449:0
               xrandr -q
: 1665428471:0
               brave --use-gl=swiftshader --disable-gpu-vsync
: 1665428518:0
               brave --use-gl=swiftshader
: 1665428573:0
               brave
: 1665430731:0
               xrandr --props
: 1665430756:0
               nvidia-settings
: 1665430986:0
               nvim /usr/share/drirc.d/00-mesa-defaults.conf
: 1665431100:0
               xrandr --props
: 1665431112:0
               xrandr --props --help
: 1665431157:0
               sudo nvidia-settings
: 1665431210:0
               xrandr -q
: 1665431214:0
               xrandr --props
: 1665431346:0
               sudoedit /etc/modprobe.d/blacklist-i915.conf
: 1665431361:0
               sudoedit /etc/mkinitcpio.conf
: 1665431372:0
               sudo mkinitcpio -P
: 1665431390:0
               nvtop
: 1665431439:0
               sudo reboot 0
: 1665431490:0
               newsboat
: 1665431490:0
               htop
: 1665431491:0
               weechat
: 1665431491:0
               gotop
: 1665431491:0
               ctop
: 1665431491:0
               xrandr --props
: 1665431495:0
               DISPLAY=:0 xrandr --props
: 1665431538:0
               sudo reboot 0
: 1665431597:0
               htop
: 1665431597:0
               ctop
: 1665431598:0
               gotop
: 1665431598:0
               newsboat
: 1665431599:0
               weechat
: 1665431642:0
               killall nextcloud
: 1665431674:0
               xrandr --props
: 1665431800:0
               nvtop
: 1665431822:0
               brave --disable-gpu-vsync
: 1665431841:0
               killall brave
: 1665431843:0
               chromium
: 1665431855:0
               brave
: 1665432140:0
               xrandr --output 'eDP-1' -r 60
: 1665432147:0
               xrandr --output 'eDP2' -r 60
: 1665432165:0
               xrandr --props
: 1665432207:0
               xrandr --output 'eDP2' --rate 60
: 1665432211:0
               xrandr --props
: 1665432228:0
               xrandr --output 'eDP2' --mode 1920x1080 --rate 60
: 1665432231:0
               xrandr --props
: 1665432558:0
               sudo systemctl enable xdg-user-dirs-update.service
: 1665432592:0
               xdg-user-dirs-update
: 1665432593:0
               ls
: 1665432648:0
               ping google.com
: 1665432733:0
               systemctl suspend
: 1665432735:0
               sudo systemctl suspend
: 1665432850:0
               sudoedit /etc/mkinitcpio.conf
: 1665432860:0
               sudo mkinitcpio -P
: 1665433158:0
               sudoedit /boot/loader/entries/arch.conf /boot/loader/entries/arch-fallback.conf
: 1665433184:0
               sudoedit /etc/pacman.conf
: 1665433530:0
               sudo systemctl status chrony
: 1665433665:0
               sudo systemctl enable thermald
: 1665433670:0
               sudo systemctl start thermald
: 1665433673:0
               sudo systemctl status thermald
: 1665433755:0
               sudo systemctl enable tlp
: 1665433758:0
               sudo systemctl start tlp
: 1665433778:0
               sudo cp ~/.histfile /arch_install/mocull_install_zsh_2.log

ls
sudo systemctl mask systemd-rfkill.service
sudo systemctl mask systemd-rfkill.socket
tlp-stat
sudo tlp-stat
sudo pacman -Syu ethtool smartmontools gsmartcontrol
sudo tlp-stat
pacman -Ss cheese
sudo pacman -Syu cheese
cheese
brave
pacman -Ss udev
xset dpms force off
xbacklight -inc 10
xbacklight -dec 10
xset dpms force off
xbacklight inc 30
xbacklight -set 50
xbacklight -set 75
xbacklight -set 10
xbacklight -set 100
cd src/
ls
nvim miscellaneous/config/sxhkd/sxhkdrc
xev
nvim miscellaneous/config/sxhkd/sxhkdrc
xev
nvim miscellaneous/config/sxhkd/sxhkdrc
helvum
systemctl --user start pipewire-pulse.service
pactl info
brave
firefox
: 1665435361:0
               sudo reboot 0
: 1665435409:0
               newsboat
: 1665435409:0
               gotop
: 1665435410:0
               ctop
: 1665435410:0
               htop
: 1665435410:0
               weechat
: 1665435461:0
               xev
: 1665435515:0
               pactl
: 1665435523:0
               pactl -- set-sink-volume 0 +10%
: 1665435529:0
               pactl -- set-sink-volume 0 +5%
: 1665435539:0
               nvim miscellaneous/config/sxhkd/sxhkdrc
: 1665435548:0
               nvim ~/src/miscellaneous/config/sxhkd/sxhkdrc
: 1665435707:0
               thermald --help
: 1665435713:0
               sudo systemctl status thermald
: 1665435763:0
               thermald --help
: 1665435780:0
               thermald status
: 1665435785:0
               sudo thermald
: 1665435788:0
               sudo thermald --help
: 1665435793:0
               ps -aux | grep -i thermald
: 1665435967:0
               cd src/miscellaneous
: 1665435968:0
               git pull
: 1665435973:0
               sudo pacman -Syu
: 1665435978:0
               ls
: 1665436002:0
               sudo cp config/chrony.conf /etc/chrony.conf
: 1665436005:0
               sudoedit /etc/chrony.conf
: 1665436466:0
               sudo systemctl stop systemd-timesyncd.service
: 1665436470:0
               sudo systemctl disable systemd-timesyncd.service
: 1665436486:0
               sudo systemctl enable chronyd.service
: 1665436502:0
               sudo systemctl enable chronyd.service
: 1665436509:0
               sudo systemctl start chronyd.service
: 1665436513:0
               sudo systemctl status chronyd.service
: 1665436536:0
               sudoedit /etc/chrony.conf
: 1665436546:0
               diff /etc/chrony.conf.pacnew /etc/chrony.conf
: 1665436550:0
               nvim -d /etc/chrony.conf.pacnew /etc/chrony.conf
: 1665436575:0
               sudoedit -d /etc/chrony.conf.pacnew /etc/chrony.conf
: 1665436653:0
               sudoedit /etc/X11/xorg.conf.d/90-tap-click.conf
: 1665437030:0
               cd /etc/X11/xorg.conf.d
: 1665437031:0
               ls
: 1665437036:0
               sudo mv 90-tap-click.conf 30-touchpad.conf
: 1665437040:0
               ls
: 1665437230:0
               lsblk --discard
: 1665437276:0
               sudo systemctl status fstrim.timer
: 1665437281:0
               sudo systemctl enable fstrim.timer
: 1665437282:0
               sudo systemctl status fstrim.timer
: 1665437290:0
               sudo systemctl start fstrim.service
: 1665437294:0
               sudo systemctl status fstrim.service
: 1665437309:0
               cat /etc/fstab
: 1665437479:0
               ls
: 1665437483:0
               sudo reboot 0
: 1665437595:0
               htop
: 1665437595:0
               weechat
: 1665437596:0
               newsboat
: 1665437596:0
               ctop
: 1665437597:0
               gotop
: 1665437664:0
               ls
: 1665437669:0
               cd src
: 1665437669:0
               ls
: 1665437671:0
               cd miscellaneous
: 1665437671:0
               ls
: 1665437673:0
               cd config
: 1665437673:0
               ls
: 1665437687:0
               ls /etc/X11
: 1665437690:0
               ls /etc/X11/xorg.conf.d
: 1665437698:0
               mkdir -p X11/xorg.conf.d
: 1665437701:0
               cd X11/xorg.conf.d
: 1665437701:0
               ls
: 1665437708:0
               sudo cp /etc/X11/xorg.conf.d/30-touchpad.conf .
: 1665437713:0
               sudo chown mocull:mocull 30-touchpad.conf
: 1665437714:0
               ls
: 1665437715:0
               ls -lah
: 1665437717:0
               cat 30-touchpad.conf
: 1665437722:0
               cd ..
: 1665437723:0
               ls
: 1665437724:0
               cd ..
: 1665437724:0
               ls
: 1665437727:0
               cat chrony.conf
: 1665437742:0
               sudo cp /etc/chrony.conf ./chrony.conf
: 1665437747:0
               sudo chown mocull:mocull chrony.conf
: 1665437751:0
               cat chrony.conf
: 1665437753:0
               git status
: 1665437756:0
               cd ..
: 1665437756:0
               ls
: 1665437760:0
               git diff
: 1665437785:0
               sudo cp ~/.histfile /arch_install/mocull_install_zsh_3.log
