return {
  -- { "tpope/vim-endwise" },
  { "tpope/vim-abolish" },
  { "tpope/vim-afterimage" },
  { "tpope/vim-apathy" },
  { "tpope/vim-characterize" },
  { "tpope/vim-dadbod" },
  { "tpope/vim-dispatch" },
  { "tpope/vim-dotenv" },
  { "tpope/vim-eunuch" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-jdaddy" },
  { "tpope/vim-obsession" },
  { "tpope/vim-projectionist" },
  { "tpope/vim-repeat" },
  { "tpope/vim-rhubarb", dependencies = { "tpope/vim-fugitive" } },
  { "tpope/vim-rsi" },
  { "tpope/vim-sensible" },
  { "tpope/vim-sleuth" },
  { "tpope/vim-speeddating" },
  { "tpope/vim-surround" },
  { "tpope/vim-tbone" },
  { "tpope/vim-unimpaired" },
  { "tpope/vim-vividchalk" },
}
