---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: forbid-submodules

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: cargo-fmt
        name: format rust
        entry: cargo fmt
        language: system
        pass_filenames: false
        types: [rust]

      # Updating accomplishes a few things:
      # - verifies dependencies are actually up to date (branch specifiers are
      #   lazily evaluated)
      # - verifies dependencies are actually used (unused dependencies or
      #   versions are removed)
      # - verifies dependencies are pinned within reason (no loose version
      #   specifiers)
      # - verifies dependencies are actually compatible (no sudden version
      #   conflicts from loose version specifiers)
      # - refreshes Cargo.lock
      - id: cargo-update
        name: update crates
        entry: cargo update
        language: system
        pass_filenames: false
        types: [toml]

      - id: cargo-test
        name: test crate
        entry: cargo test
        language: system
        pass_filenames: false
        # NOTE: `types` key is an AND operation, `types_or` key is an OR
        # operation
        # https://pre-commit.com/#filtering-files-with-types
        types_or: [rust, toml]

      - id: cargo-clippy
        name: check crate
        entry: cargo clippy
        args: [--fix, --allow-staged, --, -D, warnings]
        language: system
        pass_filenames: false
        types_or: [rust, toml]
